// Generated by software_defined_matter.glsl.emit

// part: hollow_cylinder_with_hinge

// uniforms: ['u_p_notch_radius', 'u_p_outer_radius', 'u_p_height', 'u_p_inner_radius']



uniform float u_p_notch_radius;  // notch_radius [1.0, 6.0] mm

uniform float u_p_outer_radius;  // outer_radius [10.0, 40.0] mm

uniform float u_p_height;  // height mm

uniform float u_p_inner_radius;  // inner_radius [6.0, 30.0] mm



float sdf_n0_d3(vec3 p) {
    return sdf_notch_hinge(p, 8.0, 8.0, u_p_notch_radius);
}

float sdf_n1_d3(vec3 p) {
    vec3 q = tf_translate3(p, vec3(0.0, 0.0, 30.0));
    return sdf_n0_d3(q);
}

float sdf_n2_d3(vec3 p) {
    return sdf_capped_cylinder(p, 1.0, u_p_outer_radius);
}

float sdf_n3_d3(vec3 p) {
    vec3 q = tf_translate3(p, vec3(0.0, 0.0, 29.8));
    return sdf_n2_d3(q);
}

float field_n4(vec3 p) {
    return field_radial(p, 0.25, 1.0, 0.0);
}

float sdf_n5_d3(vec3 p) {
    return sdf_n3_d3(p) + field_n4(p);
}

float sdf_n6_d3(vec3 p) {
    float d = sdf_n1_d3(p);
    d = op_union(d, sdf_n5_d3(p));
    return d;
}

float sdf_n7_d3(vec3 p) {
    return sdf_capped_cylinder(p, u_p_height, u_p_outer_radius);
}

float sdf_n8_d3(vec3 p) {
    return sdf_capped_cylinder(p, u_p_height, u_p_inner_radius);
}

float sdf_n9_d3(vec3 p) {
    float d = sdf_n7_d3(p);
    d = op_subtract(d, sdf_n8_d3(p));
    return d;
}

float sdf_n10_d3(vec3 p) {
    return sdf_gyroid(p, 8.0, 1.0, vec3(10.0, 10.0, 8.0));
}

float sdf_n11_d3(vec3 p) {
    float d = sdf_n9_d3(p);
    d = op_intersect(d, sdf_n10_d3(p));
    return d;
}

float sdf_n12_d3(vec3 p) {
    float d = sdf_n6_d3(p);
    d = op_smooth_union(d, sdf_n11_d3(p), 0.05);
    return d;
}



float sdf_scene(vec3 p) { return sdf_n12_d3(p); }
